CREATE TABLE YELPUSER
( YELPING_SINCE VARCHAR(20)
, REVIEW_COUNT INTEGER
, FIRSTNAME VARCHAR(50)
, USER_ID VARCHAR(30)
, FANS INTEGER
, AVERAGE_STARS NUMBER
, PRIMARY KEY(USER_ID)
);

CREATE TABLE USER_VOTES
( USER_ID VARCHAR(30)
, FUNNY INTEGER
, USEFUL INTEGER
, COOL INTEGER
, PRIMARY KEY (USER_ID)
, FOREIGN KEY (USER_ID) REFERENCES YELPUSER
);

CREATE TABLE YELP_USER_FRIENDS
( USER_ID VARCHAR(30)
, NUMBER_OF_FRIENDS INTEGER
, PRIMARY KEY(USER_ID)
, FOREIGN KEY(USER_ID) REFERENCES YELPUSER
);

CREATE TABLE YELP_USER_ELITE
( USER_ID VARCHAR(30)
, ELITE_YEAR INTEGER 
, PRIMARY KEY(USER_ID, ELITE_YEAR)
, FOREIGN KEY(USER_ID) REFERENCES YELPUSER (USER_ID)
);

CREATE TABLE BUSINESS
( BUSINESS_ID VARCHAR(30)
, FULL_ADDRESS VARCHAR(150)
, BUSINESS_CITY VARCHAR(25)
, REVIEW_COUNT INTEGER
, BUSINESS_NAME VARCHAR(70)
, LONGITUDE NUMBER
, BUSINESS_STATE VARCHAR(25)
, STARS NUMBER
, LATITUDE NUMBER
, PRIMARY KEY(BUSINESS_ID)
);

CREATE TABLE BUSINESS_CATEGORIES
( BUSINESS_ID VARCHAR(30)
, CATEGORIES VARCHAR(30)
, SUBCATEGORIES VARCHAR(50)
, PRIMARY KEY(BUSINESS_ID, CATEGORIES, SUBCATEGORIES)
, FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS
);

CREATE TABLE NEIGHBORHOOD
( BUSINESS_ID VARCHAR(30)
, NEIGHBORHOOD VARCHAR(30)
, PRIMARY KEY(BUSINESS_ID, NEIGHBORHOOD)
, FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS
);

CREATE TABLE REVIEW
( TOTAL_VOTES NUMBER
, USER_ID VARCHAR(30) 
, REVIEW_ID VARCHAR(30)
, STARS NUMBER
, REVIEW_DATE VARCHAR(20)
, BUSINESS_ID VARCHAR(30)
, TEXT CLOB
, PRIMARY KEY(USER_ID, REVIEW_ID, BUSINESS_ID)
, FOREIGN KEY(USER_ID) REFERENCES YELPUSER (USER_ID)
, FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS (BUSINESS_ID)
);

CREATE TABLE CHECK_IN
( BUSINESS_ID VARCHAR(30)
, DAYOF INTEGER
, FROMHOUR INTEGER
, CHECKINCOUNT INTEGER
, PRIMARY KEY(BUSINESS_ID, DAYOF, FROMHOUR)
, FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS
);